apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: maud

namespace: maud

resources:
  - namespace.yaml
  - maud-deployment.yaml
  - maud-service.yaml
  - mongo-deployment.yaml
  - mongo-service.yaml
  - mongo-pvc.yaml
